services:
  socks5:
    image: 3proxy/3proxy:latest
    container_name: Fiverr-Dedicated-IP
    restart: always
    ports:
      - "1080:1080"
    volumes:
      - ./fiverr-socks5.sh:/fiverr-socks5.sh
    entrypoint: ["/bin/sh", "/fiverr-socks5.sh"]
