services:
  socks5:
    image: 3proxy/3proxy:latest
    container_name: Fiverr-Dedicated-IP
    restart: always
    ports:
      - "${S5_PORT}:${S5_PORT}"
    volumes:
      - ./fiverr-socks5.sh:/fiverr-socks5.sh
    # 注意：这里去掉了 tty 和 stdin_open，因为我们不在容器里交互了
    entrypoint: ["/bin/sh", "/fiverr-socks5.sh"]
